apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - prometheus-deployment.yaml
images:
  - name: DOCKERHUB_USERNAME/nginx-app
    newName: DOCKERHUB_USERNAME/nginx-app
  - name: DOCKERHUB_USERNAME/backend-app
    newName: DOCKERHUB_USERNAME/backend-app
  - name: DOCKERHUB_USERNAME/frontend-app
    newName: DOCKERHUB_USERNAME/frontend-app
